# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f53b56fa8ecb91ec748dde24ac64664f04e7f4906b4053de39ea82ba76c586acb0b18ff20e84119f9bac1324697fb5d95ec2e075bb3a8f2685bc2f12bc8d83a

test:
  secret_key_base: 30b348dc8837bd5551c05570bc1547de2b0b0062568bda6a6b80ff5f1d9224d7db98e11e5c7ce90ddee08b159ea2db8e9149b7cf1de56765e53ce51a9c4a3ae5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
