source "https://rubygems.org"

# Declare your gem's dependencies in shaving.gemspec.
gemspec

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', '~> 0.4.0'
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'byebug'
end

